version: '0.1'

services
  eureka-server
    build: eureka-server
    mem_limit: 256m
    ports:
      - "8761:8761"
    networks:
      - 'appliance-network'
  
  config-server
    build: config-server
    mem_limit: 256m
    ports:
      - "8888:8888"
    networks:
      - 'appliance-network'

  api-gateway
    build: api-gateway
    mem_limit: 512m
    ports:
      - "8080:8080"
    networks:
      - 'appliance-network'

  products-service
    build: products-service
    mem_limit: 512m
    ports:
      - "8082:8082"
    networks:
      - 'appliance-network'
  
  sales-service
    build: sales-service
    mem_limit: 512m
    ports:
      - "8084:8084"
    networks:
      - 'appliance-network'
  
  shopcart-service
    build: shopcart-service
    mem_limit: 512m
    ports:
      - "8086:8086"
    networks:
      - 'appliance-network'
        
networks:
  appliance-network: